events {
}

http {
    server {
        listen 80;

        client_max_body_size 5M;

        location = /images/ {
            proxy_pass http://app:8000;
        }

        location /images/ {
            alias /images/;
        }

        location / {
            proxy_pass http://app:8000;
        }
    }
}